[package]
name = "raudius-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
ethcontract = "0.23.2"
futures = "0.3"
mongodb = "2.4"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
