//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "audio_transactions_history")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_bank: String,
    pub slot: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub signature: String,
    pub transaction_type: String,
    pub method: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub transaction_created_at: DateTime,
    pub change: Decimal,
    pub balance: Decimal,
    pub tx_metadata: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
