//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "chat_blocked_users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub blocker_user_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub blockee_user_id: i32,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
