//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_tips")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub slot: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub signature: String,
    pub sender_user_id: i32,
    pub receiver_user_id: i32,
    pub amount: i64,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
