/*
 * API
 *
 * Audius V1 API
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Activity {
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "item_type", skip_serializing_if = "Option::is_none")]
    pub item_type: Option<serde_json::Value>,
    #[serde(rename = "item", skip_serializing_if = "Option::is_none")]
    pub item: Option<serde_json::Value>,
}

impl Activity {
    pub fn new() -> Activity {
        Activity {
            timestamp: None,
            item_type: None,
            item: None,
        }
    }
}
