/*
 * API
 *
 * Audius V1 API
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */
use fake::{Dummy, Fake};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, Dummy)]
pub struct ListenCount {
    #[serde(rename = "trackId", skip_serializing_if = "Option::is_none")]
    pub track_id: Option<i32>,
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "listens", skip_serializing_if = "Option::is_none")]
    pub listens: Option<i32>,
}

impl ListenCount {
    pub fn new() -> ListenCount {
        ListenCount {
            track_id: None,
            date: None,
            listens: None,
        }
    }
}
