/*
 * API
 *
 * Audius V1 API
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TrackElement {
    #[serde(rename = "parent_track_id")]
    pub parent_track_id: String,
}

impl TrackElement {
    pub fn new(parent_track_id: String) -> TrackElement {
        TrackElement { parent_track_id }
    }
}
