/*
 * API
 *
 * Audius V1 API
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserTrackListenCountsResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<::std::collections::HashMap<String, crate::api::MonthlyAggregatePlay>>,
}

impl UserTrackListenCountsResponse {
    pub fn new() -> UserTrackListenCountsResponse {
        UserTrackListenCountsResponse { data: None }
    }
}
