/*
 * API
 *
 * Audius V1 API
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */
use fake::{Dummy, Fake};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, Dummy)]
pub struct VersionMetadata {
    #[serde(rename = "service")]
    pub service: String,
    #[serde(rename = "version")]
    pub version: String,
}

impl VersionMetadata {
    pub fn new(service: String, version: String) -> VersionMetadata {
        VersionMetadata { service, version }
    }
}
